org.gradle.jvmargs = -Xmx12G -Dfile.encoding=UTF-8
org.gradle.daemon  = false

#Mod（按你的模组填写）
group              = moe.forpleuvoir
mod_name           = Compose Minecraft
mod_author         = forpleuvoir
mod_id             = compose_minecraft
license            = Apache-2.0
description        = Compose Minecraft mod
credits            =
version            = 0.1.0
